CVEProject/cve-website

docker/Dockerfile, docker/Dockerfile-static
They're now served when using either `serve` or `build` from inside docker. The Nginx container hasn't been tested, but the application container has.
=> Update docker to include top-level public assets

src/assets/data/navigation.json
Updated resources and support button to now go to 'Resources' page (first link) instead of Report/Request page
=> #171 Resources and Support Button

src/views/Downloads.vue
Updated CVRF download links to go to old website (previously the links sent to a 404).
#166
=> #166 Updated CVRF links to old website

src/components/HomeModule.vue, src/components/HomePageSidebarModule.vue
A quick note: the change to HomePageSidebarModule was in response to "And" in "CVE Outreach and Communications..." being auto capitalized before the change (imaged below).
I think the only implication that changing `<p class="">{{event.title}}</p>` from `<p class="is-capitalized">{{event.title}}</p>` is that capitalization of event titles in events.json needs to be done accurately.
#190
=> #190 Homepage changes suggested by Rob

src/views/ProgramOrganization/Board.vue
Replace broken Nabble link with new Mail-Archive.com link
=> #399 Replace Board Mail Archive link

src/assets/data/navigation.json, src/views/About/RelatedEfforts.vue
IMPORTANT:   I was unable to update the <h2> for the Adversarial Tactics, Techniques & Common Knowledge (ATT&CK™) section.  
There was a name change (it's no longer spelled-out) so we need to change it to just the acronym "ATT&CK®" with an registered trademark. 
On-page navigation needs to be updated with the same change too.
=> #449 Related Efforts page per Final Reviewer Comments

src/assets/data/NotificationBanner.json, src/components/NotificationBannerModule.vue
Updated the "transition" link in the banner message to go to an internal link.
Can you please remove the extra blank space between the word 'transition' and the end period?
=> Content rjr 607

src/views/ProgramOrganization/WorkingGroups.vue, src/views/ResourcesSupport/Resources.vue
Links are for the Spanish translations of the CNA Onboarding videos, which are currently hosted on the old website.
For the 11/23 release.
=> #661 Add links to Resources for 7 Spanish videos

src/views/ProgramOrganization/WorkingGroups.vue, src/views/ResourcesSupport/Resources.vue
Working Groups page - add embedded YouTube file (same as how on About page, but smaller frame).
Resources page:
- add link to the WGs podcast episode page as a WGs resource item.
- add link to the Researchers podcast episode page as a Researchers resource item.
=> #1007 Update WGs & Resources pages with podcasts

src/components/NavigationSidebar.vue, src/components/NewsModule.vue, src/views/Media/News/BlogArchives.vue, src/views/Media/News/NewsArchives.vue
Expected behaviors:
- right nav appears on all News-related pages in touch devices: All News, Recent: News, Blogs, Podcasts, Archives: News Articles, Blogs
=> #1147 display right nav on news-related pages on touch screens

src/assets/data/navigation.json, src/components/NewsModule.vue, src/views/Media/News/BlogArchives.vue, src/views/Media/News/Blogs.vue, src/views/Media/News/News.vue, src/views/Media/News/NewsArchives.vue, src/views/Media/News/NewsItem.vue, src/views/Media/News/Podcasts.vue
Please test all news-related pages: 1) that the survey link is present and 2) it goes to the corresponding MS form survey link.
=> #1027 add ability to link custom feedback form for each of the news types

src/assets/data/CNAsList.json
Please see: [Issue 1684 ](https://github.com/CVEProject/cve-website/issues/1684)
This PR updates the URLS associated with `CNA-2020-0030` from the 3.2 -> 4.0 versions. The previous 3.2 urls were returning AccessDenied.
=> Update the URLS for CNA-2020-0030 to point to most recently updated ones

src/App.vue, src/assets/data/glossaryEntries.json, src/components/SearchTable.vue, src/router/index.js, src/views/ResourcesSupport/Glossary.vue
Closes #2938 
Redesigned the Glossary page to show terms and definitions in a table view. Each term can be linked and will be scrolled to when links are accessed from other pages.
=> Resolves #2938 Redesign and simplify glossary table

src/components/AdpVulnerabilityEnrichment.vue
Closes #2931 
Added `toFixed(1)` to CVSS scores shown on the CVE Record details page, as CVSS scores should always have 1 decimal place.
=> Resolves #2931 Added `toFixed(1)` to CVSS score displays

src/assets/style/globals.scss, src/components/AdpVulnerabilityEnrichment.vue
Fixed title text in cnaContainers so they wrap to a new line instead of overflowing out of the container.
=> Resolves #2932 Fixes title overflow in cnaContainer 

src/views/CVERecord/PublishedRecord.vue
Changed the updated date in the CNA container on the CVE record page to use the cnaContainer's date updated.
=> Resolves #3018 Show cnaContainer date updated instead of full CVE record date updated

src/assets/style/globals.scss, src/components/AdpVulnerabilityEnrichment.vue, src/components/NotificationBannerModule.vue, src/components/TableOfContentsSidebar.vue, src/stores/cveRecordLookup.ts, src/views/About/Process.vue, src/views/CVERecord/PublishedRecord.vue, src/views/CVERecord/RejectedRecordOrId.vue, src/views/CVERecord/ReservedId.vue, src/views/Media/News/BlogArchives.vue, src/views/PartnerInformation/ListofPartners.vue, src/views/PartnerInformation/Partner.vue, src/views/ProgramOrganization/Board.vue, src/views/ReportRequest/ReportRequestForNonCNAs.vue, src/views/ResourcesSupport/AllResources/CveServices.vue, src/views/ResourcesSupport/FAQs.vue
Previously, to collapse or expand a container on the CVE record details page, the +/- button had to be clicked. Now, any where on the container header can be clicked to expand/collapse.
`globals.scss`
- Removed h1,2,3,4,5,6 color styling. No longer needed as default font color is black and it overwrote other styling
`AdpvulnerabilityEnrichment.vue`
- Replaced accordion div with button
- Fixed typos
- Removed toggle function from +/- button and added it to the accordion button
Multiple files
- Fixed accordion typo
=> Resolves #3000 Accordion container headers can be clicked anywhere to toggle

src/views/About/Metrics.vue
The CNAs added by Year table on the Metrics page had column titles displayed in the wrong font color. This was addressed by adding the correct <tr> tags.
`Metrics.vue`
- Added `<tr>` under `<thead>` so the correct styling is applied.
=> Resolves #3080 Fixed column title color for CNAs added by Year table

src/components/AdpVulnerabilityEnrichment.vue, src/views/CVERecord/RejectedRecordOrId.vue
Added red badge styling to Active SSVCs. Other SSVC types remain plain text.
Also resolves #2999 
- Added dynamic classes to add styiling
=> Resolves #2955 Added red badge styling to Active SSVCs

src/views/CVERecord/CveRecordUserGuide.vue
Changed the incorrect URL anchor from `versions-and-version-ranges` to `source-control-versions` in `CveRecordUserGuide.vue`.  Confirmed that the changed anchor brings up the correct section ("Source Control Versions") in the document.
=> Resolves #2927 correct anchor in link for source control versions in user guide (int-main branch)

src/views/CVERecord/CveRecordUserGuide.vue
Changed the incorrect URL anchor from `versions-and-version-ranges` to `source-control-versions` in `CveRecordUserGuide.vue`.  Confirmed that the changed anchor brings up the correct section ("Source Control Versions") in the document.
=> Resolves #2927 correct anchor in link for source control versions in user guide (dev branch)

src/components/AdpVulnerabilityEnrichment.vue
The **Description** header under the **CNA** tab scrolled along with the description text if a very long URL was included in the text.  This was corrected by removing the header from the `cve-x-scroll` class, so that only the paragraph containing the text is scrollable.  This was tested by launching the sample CVE record and manually adding a very long URL into the description text, long enough to create a scrollbar.  The **Description** header remains fixed (doesn't scroll).
=> Resolves #2926 prevent Description heading from scrolling with text (int-main branch)

src/components/AdpVulnerabilityEnrichment.vue
The **Description** header under the **CNA** tab scrolled along with the description text if a very long URL was included in the text.  This was corrected by removing the header from the `cve-x-scroll` class, so that only the paragraph containing the text is scrollable.  This was tested by launching the sample CVE record and manually adding a very long URL into the description text, long enough to create a scrollbar.  The **Description** header remains fixed (doesn't scroll).
=> Resolves #2926 prevent Description heading from scrolling with text (dev branch)

src/components/HomeModule.vue, src/views/About/History.vue, src/views/About/Overview.vue, src/views/ResourcesSupport/Resources.vue
Adds target="_blank" to 4 PDF links that were causing 404 errors (page not found).
Resolves #3268
=> #3268 Update 4 PDF urls (#3269)

src/assets/style/globals.scss, src/components/AdpVulnerabilityEnrichment.vue, src/components/CveRecordReferences.vue, src/components/ProductStatus.vue
Added scrolling and borders to the References section of the published CVE record view. This styling matches other potentially long sections in the CVE record view, like versions.
Also, centralized related styling and SCSS to be global and reused across related sections.
`src/components/CveRecordReferences.vue`
- Added `cve-scroll-box` to add scrolling and border styling
- Added tag displaying total reference count
`src/components/AdpVulnerabilityEnrichment.vue` 
- Globalized certain scroll styling from existing scroll containers
=> Resolves #3077 Added scrolling to references list on publish records

src/assets/style/globals.scss, src/components/AdpVulnerabilityEnrichment.vue, src/components/CveRecordReferences.vue, src/components/ProductStatus.vue
Added scrolling and borders to the References section of the published CVE record view. This styling matches other potentially long sections in the CVE record view, like versions.
Also, centralized related styling and SCSS to be global and reused across related sections.
`src/components/CveRecordReferences.vue`
- Added `cve-scroll-box` to add scrolling and border styling
- Added tag displaying total reference count
`src/components/AdpVulnerabilityEnrichment.vue` 
- Globalized certain scroll styling from existing scroll containers
=> Resolves #3077 Dev version of PR #3193

src/components/AdpVulnerabilityEnrichment.vue
Added checks to account for situations when a record doesn't have `providerMetadata` fields. These fields are technically not required by the schema, but are generated by CVE-Services when records are published, EXCEPT for records created by the Secretariat endpoint. So this change accounts specifically for that edge case.
`src/components/AdpVulnerabilityEnrichment.vue`
- Added check for missing providerMetadata
=> Resolves #2911 Added check for edge case when providerMetadata fields aren't provided

src/components/AdpVulnerabilityEnrichment.vue
Added checks to account for situations when a record doesn't have `providerMetadata` fields. These fields are technically not required by the schema, but are generated by CVE-Services when records are published, EXCEPT for records created by the Secretariat endpoint. So this change accounts specifically for that edge case.
`src/components/AdpVulnerabilityEnrichment.vue`
- Added check for missing providerMetadata
=> Resolves #2911 Dev version of PR #3222

src/assets/data/navigation.json
After a lot of searching and experimenting, it all boiled down to removing the "items" element from the "Structure" object in `navigation.json`.  I also made a spelling correction that has no reference elsewhere.  I've tested that the `Structure` entry in the `Program Organization` navigation sidebar has no expand button.
=> Resolves #2964 remove expand button (+) from Program Organization -> Structure (int-main)

src/assets/data/navigation.json
After a lot of searching and experimenting, it all boiled down to removing the "items" element from the "Structure" object in `navigation.json`.  I also made a spelling correction that has no reference elsewhere.  I've tested that the `Structure` entry in the `Program Organization` navigation sidebar has no expand button.
=> Resolves #2964 remove expand button (+) from Program Organization -> Structure (dev)

src/components/NavigationSidebar.vue
A paragraph was used in the navigation sidebar for accessibility text (collapse/expand) on the -/+ button icons.  This was causing the icon to become off-centered in the button.  This change switches the accessibility text to the SVG's "title" element, which makes the icons centered in the buttons, correcting the original problem.
=> Resolves #2783 - center highlight on expand/collapse buttons (int-main)

src/views/Downloads.vue
The width of the navigation sidebar on the Downloads page was larger than the equivalent sidebars on the other pages.  I was able to correct the width on this page by adding a missing class attribute.
=> Resolves #1910 - Downloads Navigation Sidebar Width Correction (int-main)

src/views/Downloads.vue
The width of the navigation sidebar on the Downloads page was larger than the equivalent sidebars on the other pages.  I was able to correct the width on this page by adding a missing class attribute.
=> Resolves #1910 - Downloads Navigation Sidebar Width Correction (dev)

src/stores/cveListSearch.js, src/views/CVERecord/SearchResults.vue
The "CNA" fields on the Search Results page is unexpectedly not rendering the CNA long name, rather just the CNA short name else, "No CNA provided."
src/stores/cveListSearch.js
- Added `cnaOrgId` to get the org id for the individual records in the search results or when a CVE Record is Found
src/views/CVERecord/SearchResults.vue
- Update rendering logic to check if the `cnaOrgId` exists in the `usePartnerStore`, then display the corresponding CNA long name, else display the CNA short name or "No CNA provided." if the short name does not exist.
=> Resolves #3314 fix CNA long name in Search Results page (dev)

src/stores/cveListSearch.js, src/views/CVERecord/SearchResults.vue
Please see description for issue #3340. It's a continuation of #3314.
src/stores/cveListSearch.js
- `cna` and `cnaOrgId` switched to using the `containers.cna.providerMetadata` `shortName` and `orgId` properties
src/views/CVERecord/SearchResults.vue
- created `partnerStore` object and accessing `partnerShortLongNameMap` property to get CNA long name by Id.
**UI**
Same as #3314
=> #3340 fix CNA long name and update CNA shortname (dev)

src/stores/cveListSearch.js, src/views/CVERecord/SearchResults.vue
Please see description for issue #3340. It's a continuation of #3314.
src/stores/cveListSearch.js
- `cna` and `cnaOrgId` switched to using the `containers.cna.providerMetadata` `shortName` and `orgId` properties
src/views/CVERecord/SearchResults.vue
- created `partnerStore` object and accessing `partnerShortLongNameMap` property to get CNA long name by Id.
**UI**
Same as #3314
=> #3340 fix CNA long name and update CNA shortname (int)

src/components/SearchTable.vue, src/router/index.js, src/views/ResourcesSupport/AllResources/CNARules.vue
Scrolling to anchors on certain pages like Glossary and CNA Rules would sometimes scroll the target anchor out of view. This specifically happened when navigating to the sight externally. 
Also, this updates the CNA Rules page to have links directly on each section title and not just in the table of contents.
`index.js`
- Specified `scrollBehavior`
- Wrapped behavior in promise and added `setTimeout` of 0. This works.
- Added navigation guard for the glossary route to update the route hash when activeTerm is used instead.
`SearchTable.vue`
- Replaced `<a>` with `vue-router`
- updated behavior to not reload the page when clicking on a term
- simplified `mount()` behavior
`cnaRules.vue`
- Added anchors to each section and subsection
- Added CSS to make each `li` …
=> Resolves #2821 Fixes scrolling to anchors

src/views/CVERecord/PublishedRecord.vue
Removed the capitalization of "words" in the CNA name displayed in the returned record.  The displayed CNA name is as it exists in the database.
Closes #3017
=> Resolves #3017 - Correct Render CNA Names (int)

src/views/CVERecord/PublishedRecord.vue
Removed the capitalization of "words" in the CNA name displayed in the returned record.  The displayed CNA name is as it exists in the database.
Closes #3017
=> Resolves #3017 - Correct Render CNA Names (dev)

src/views/About/Metrics.vue
This change overrides the CSS for tables in cveTableStacked.scss, which is really meant for tables used like a "bordered section of content" - see the Resources page.  The metrics page is truly tabular data and the style doesn't work in mobile views.  The CSS added to the Metrics module reverses the effect and displays the tables the same in mobile view as in a full desktop view.  Horizontal scrolling is used if the table it too large for the display area.
Closes #3081
Closes #2900
=> Resolves #3081 - metrics: fix tables in mobile view (int)

src/assets/data/navigation.json, src/components/PrimaryNavigation.vue
Data for the primary menu is in `navigation.json`.  The PrimaryNavigation module creates the main menu and determines from the data the menu items and the popup submenus.  There are no menu items for "All Resources" and "CVE Services" in the primary menu, but the submenus for those were showing up if the mouse pointer was in the right position.  The change corrects this such that those "ghost" submenus no longer appear.
Closes #2273
=> Resolves #2273 - Prevent "ghost" submenus in primary navigation menu (int)

src/views/CVERecord/SearchResults.vue
The search page has a summary showing results like:
"Showing x of y results"
when the total is 1, the plural is still shown.  This change corrects this case.
Closes #3389
=> Resolves #3389 - Handle Plural of "results" in Summary

index.html, package-lock.json, package.json, public/robots.txt, src/App.vue, src/components/HomeModule.vue, src/main.ts
Added `unhead` package as a dependency for adding meta data to the header.
Used `unhead` to add title & description
Added canonical link for cve.org
Added alt text for CVE Partnership graphic
All the above were recommended by seobility.net & seoptimizer.com
First test in the TEST instance, where we'll run the analysis again.
=> SEO: add "unhead" for meta; add title, heading, & description (TEST)
