package.json
src/components/FooterModule.vue
src/main.js

Initial version of footer ready to merge

Initial version of footer

---

src/App.vue
src/assets/style/colors.scss
src/assets/style/globals.scss
src/components/HomeModule.vue
src/components/HomePageSidebarModule.vue
src/components/PrimaryNavigation.vue
src/components/Search.vue
src/views/ListSearch.vue

Initial integration of USWDS colors

switched to used USWDS theme colors, defined in colors.scss

---

docker/.env-docker
docker/Dockerfile-static

Modified docker build for static file to specify localhost as the base URL inside the .env file.

Added new env settings for static docker site

---

src/assets/data/navigation.json

#264 renumber navigation items

---

src/assets/style/globals.scss
src/views/PartnerInformation/ListofPartners.vue
src/views/PartnerInformation/PartnerDetails.vue

Reverts CVEProject/cve-website#334

Revert "#277 add country column to table on list of partners page"

---

src/assets/data/news.json
src/views/Media/News.vue

Added nine (9) news items for the v1.0 launch and fixed 2 lines of code in News.vue.
News item 9 will be updated prior to the v1.0 launch, once the text has been finalized and approved.

Content rjr 409

---

src/assets/data/NotificationBanner.json

Per the Final Review Comment, update banner announcement to a link to more info + specified keyword search is on old website

#435 add transition link + specify keyword search

---

src/assets/data/faqs.json
src/views/ResourcesSupport/FAQs.vue

Updated the FAQs per the Final Reviewer's comments. Also, add the missing "s" in "Collapse All" button text in FAQs.vue.

#439 update FAQs text + fix typo on FAQs.vue

---

src/views/PartnerInformation/ListofPartners.vue

Intro text + "Organization Types" section of expandable box

#452 Update List of Partners page intro text per Final Reviewer Comments

---

src/views/ProgramOrganization/CNAs.vue

I also updated the CNA Program stats to be current as of 9/14/2021

#466 Update CNAs page per Final Reviewer Comments

---

src/views/ResourcesSupport/ReportRequest.vue

**IMPORTANT:**   Please change the "Request a CVE Record" header & on-page navigation to instead say "Update a CVE Record".
I am unable to make the change myself.

#468 Update Report/Request page per Final Review Comments

---

src/views/ResourcesSupport/Resources.vue

Can the **Requester/Researcher Resources** box be widened slightly, to accommodate the new descriptive text under each of the three items?

#470 Update Resources page per Final Review Comments

---

src/assets/data/faqs.json
src/components/FooterModule.vue

This is for item (3) in Issue #479, for the text updates. 
The images in items (1) and (2) of #479 still need to be replaced by a developer.

#479 Update CVE logo trademark statements in Footer & 1 FAQ answer

---

src/views/ResourcesSupport/ReportRequest.vue
src/views/ResourcesSupport/Resources.vue

On (1) Report/Request page, and (2) Resources page.

#481 Remove links to 'Researcher Reservation Guidelines' doc

---

src/assets/data/CNAsList.json
src/views/About/History.vue
src/views/PartnerInformation/PartnerDetails.vue
src/views/ProgramOrganization/Structure.vue

3 new CNAs added + corrected info and other text content updates

#490 Updated CNAsList.json as of 9/22/21

---

src/views/CVERecord.vue

#516 hide problem type field when it's empty

---

src/assets/data/news.json
src/views/ProgramOrganization/CNAs.vue

+ Edits to intro and other text in CNA Program Growth section, per OCWG.

#512 Updated CNA Growth stats to add 5 new CNAs

---

src/assets/data/CNAsList.json

+ minor edits to 3 other entries.

#515 Add 5 new CNAs to CNAsList.json

---

src/views/Home.vue
src/views/ResourcesSupport/ReportRequest.vue

Added " target="_blank" to external links on both pages as indicated. Fixed broken link for word "Download" on homepage.

#543 Update links on Home & Report Request

---

src/assets/data/events.json

Add 1 new event to Past events

#551 Add 1 new Event

---

src/assets/data/CNAsList.json

(1) Added 1 new CNA
(2) Updated JFrog scope
(3) Updated Israel National Cyber Directorate advisory link
(4) Made several other minor updates

#545 Update Partners List to add 1 new CNA

---

src/assets/data/news.json

+ edits to the JFrog article to update its scope per its recently updated partner details page

#549 Add 1 News article for the new CNA

---

src/views/ResourcesSupport/Resources.vue

(1) Updated CNACWG charter link from version 1.3 to 1.4
(2) Added target="_blank" to links where needed

#541 Update Resources page links

---

src/assets/data/CNAsList.json
src/assets/data/news.json
src/views/Media/News.vue
src/views/Media/NewsItem.vue

error in second commit message - should refer to #571 not 573

Content rjr 571

---

src/assets/data/faqs.json

Updated "How can I encrypt my requests via the form?" and "How do I contact the CVE Program?" FAQs. 
Also made other minor edits to other FAQs.

#601 Update 2 FAQs and other minor edits

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Add 1 new to CNAsList + 1 new to News

Content rjr 637

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Add 4 new CNAs, remove 1 CNA, updates to 2 CNAs, and add 4 News articles (for the 4 new CNAs)

Content rjr 658

---

src/views/ProgramOrganization/WorkingGroups.vue

Updated the WGs page to better emphasize the TWG text. Also, made one minor word change to the intro text.

#671 Two minor edits to WG page

---

src/views/ProgramOrganization/WorkingGroups.vue

Updated the WGs page to better emphasize the TWG text. Also, made one minor word change to the intro text.

Content rjr 671

---

src/assets/data/CNAsList.json

Email update, scope update, and 4 url updates. 
For the 11/23 release.

#676 Update detail pages for 3 CNAs

---

src/assets/data/news.json

Fix 1 news headline for the 11/23 release

Content rjr 690

---

src/views/ProgramOrganization/WorkingGroups.vue

Fixed 3 PDF urls. Also, adjusted some line endings so they don't extend past 150 characters.

#684 Fix PDFs to open new browser tab on WGs page

---

src/views/ProgramOrganization/WorkingGroups.vue

Fixed 3 PDF urls to open new browser tab on WGs page. Also, adjusted some line endings so they don't extend past 150 characters.

Content rjr 684

---

src/assets/data/news.json

Podcast article added for the 11/30 release.

#693 Add Podcaast article for the 11/30/21 release

---

src/assets/data/news.json

Podcast article added for the 11/30/21 release.

Content rjr 693

---

src/views/ResourcesSupport/Resources.vue

Update intro text + 1 video's description on Resources page
For the 12/7 release

#709 Update Onboarding Videos table intro text

---

src/assets/data/news.json

For the 12/7 release:
Added name in RedHat podcast
Fixed ordering of 8/17/2021 blog and 8/24/2021 podcast

#710 Update name in article & fix article order

---

src/assets/data/news.json

For the 12/7 release:
Added name in RedHat podcast
Fixed ordering of 8/17/2021 blog and 8/24/2021 podcast

Content rjr 710

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Update CNAs list and News page to add 2 new CNAs + 1 update 1 CNA.
No CNA World Map update for the 12/7 release.

#711 Add 2 new CNAs & update 1 CNA

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Update CNAs list and News page to add 2 new CNAs + 1 CNA update.
No CNA World Map update for the 12/7 release.

Content rjr 711

---

src/assets/data/CNAsList.json
src/assets/data/events.json
src/assets/data/news.json

Add 1 new Blog + 1 new link in Events for the 12/7 release

Content rjr 726

---

src/assets/data/events.json
src/components/HomePageSidebarModule.vue
src/views/Media/Events.vue

new JSON format and code are ready to go. Final archive data needs to be added to events.json when ready

#648 Add archives to Events page

---

src/assets/data/news.json

Add 1 new Blog article for the 12/14 release

Content rjr 736

---

src/assets/data/events.json
src/assets/data/navigation.json
src/assets/data/news.json
src/components/HomePageSidebarModule.vue
src/components/NavigationSidebar.vue
src/components/NewsModule.vue
src/router/index.js
src/views/Media/Events.vue
src/views/Media/News/AllNews.vue
src/views/Media/News/Blogs.vue
src/views/Media/News/News.vue
src/views/Media/News/NewsArchives.vue
src/views/Media/News/NewsItem.vue
src/views/Media/News/Podcasts.vue

Add 1 new Podcast & update 1 existing Podcast

Content rjr 727

---

src/assets/data/news.json

(1) Add 6 Blog archive PDFs 
(2) Fix 1 existing PDF url  to add missing 'r' in word 'for' in:
"/Resources/Media/Archives/Blogs/2021/2021-07-28_CVE-Program-Report-for-Q2-Calendar-Year-2021.pdf"

#747 Add 6 Blog PDFs + Fix 1 existing PDF url

---

src/assets/data/CNAsList.json
src/assets/data/news.json

For the 12/21 release:
(1) Add 3 new CNAs
(2) Remove 1 CNA
(3) Add 3 new News articles for the new CNAs
(4) CNAs Word Map already updated

#761 Add 3 new & delete 1 CNA + add 3 news article

---

src/assets/data/CNAsList.json
src/assets/data/news.json

For the 12/21 release:
(1) Add 3 new CNAs
(2) Remove 1 CNA
(3) Add 3 new News articles for the new CNAs
(4) CNAs World Map already updated

Content rjr 761

---

src/assets/data/news.json
src/views/Downloads.vue

Updated Downloads page with notification message linking to the News page announcement article.
Also, reordered the news articles to restore the new website article # to September.

#749 Downloads changing page notice + News article

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#789 Add 1new+delete1CNA+2 otherCNAupdates+1News

---

src/assets/data/CNAsList.json
src/assets/data/news.json
src/views/Downloads.vue

Fix typo in new CNA news article for 1/11/22

Content rjr 794

---

src/assets/data/news.json

#798 Blog article about Downloads Changing

---

src/assets/data/news.json

Blog article about Downloads Changing for the 1/18/2022 site update

Content rjr 798

---

src/assets/data/news.json

The new blog article about the Downloads changing should be first, and this article about the 1/5/22 Board meeting minutes should be second for the 1/18/22 release

#800 Add 1 new News article + update 1 article

---

src/assets/data/news.json

Add 1 new News article + update 1 article
NOTE: The new blog article about the Downloads changing should be first, and this article about the 1/5/22 Board meeting minutes should be second for the 1/18/22 release

Content rjr 800

---

src/views/About/Process.vue

Add 1 link out to the CNAs list on the Process page for the 1/25 release.

Content rjr 813

---

src/assets/data/currentBoardMembersList.json

Update organization for 1 Board member

Content rjr 818

---

src/assets/data/news.json

3 updates for the 1/25/22 release:
1.  Add 1 new article about the 1/19/22 Board meeting minutes.
2. Update 1 news article with a link to a press release.
3. Update 1 url in 1 news article.

#823 Add 1 new + update 2 articles on News page

---

src/assets/data/news.json

3 updates to the News page for the 1/25/22 release:
1. Add 1 new article about the 1/19/22 Board meeting minutes.
2. Update 1 news article with a link to a press release.
3. Update 1 url in 1 news article.

Content rjr 823

---

src/assets/data/events.json

for the "CVE Summit - Spring 2022"

#824 Add 1 new Event

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Add 1 new Blog article + update 3 CNAs for adding the new Root

Content rjr 819

---

src/assets/data/news.json
src/views/About/Process.vue
src/views/ProgramOrganization/Board.vue
src/views/ResourcesSupport/Resources.vue

Update urls for Board Charter PDF and Board New Member Nomination Form on 3 pages:
1. News article about Board Charter 3.4
2. Board page
3. Resources page

#803 Update Board Charter+Nom form urls on 3 pages

---

src/views/ResourcesSupport/Resources.vue

@slubar, PLEASE ALSO temporarily remove "/Resources/General/Policies/RBP-CVE-IDs-Policy.pdf"

#835 Remove RBP Policy item from Resources page

---

src/assets/data/currentBoardMembersList.json

Update organization for 1 Board member

Content rjr 844

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Add 1 new CNA + update 1 existing CNA

Content rjr 845

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Update DIVD CNA's scope on detail pg & News

Content rjr 852

---

src/assets/data/news.json

Removed RBP link from News article

Content rjr 839

---

src/assets/data/navigation.json
src/views/About/Metrics.vue

please refer to "2-2-2022 METRICS page revam...and " "2-4-2022 Metrics page" Word doc for updates

#842 update metrics tables

---

src/assets/data/events.json

Content rjr 865

---

src/assets/data/CNAsList.json
src/assets/data/news.json

1.  Added 1 new CNA.
2.  Added on News page:
- 1 new CNA announcement article.
- Updated the 2 other CNA announcement articles posted in 2022.
3.  Note: No CNA Map update.

#868 Add 1 new CNA

---

src/assets/data/CNAsList.json
src/assets/data/news.json

1.  Added 1 new CNA.
2.  Added on News page:
- 1 new CNA announcement article.
- Updated the 2 other CNA announcement articles posted in 2022.
3.  Note: No CNA Map update.

Content rjr 868

---

src/views/About/Metrics.vue

Updated 2 stats + revised CNA vs CNA-LRs table rows

#889 Update Metrics page

---

src/assets/data/faqs.json

Content rjr 894

---

src/assets/data/CNAsList.json

Update Google Root and Android CNA info

Content rjr 903

---

src/assets/data/news.json

Content rjr 905

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Add 1 new CNA + News announcement

Content rjr 911

---

src/assets/data/CNAsList.json

Update contact email for Wordfence CNA for the 3/8/22 release

#920 Update 1 CNA's contact email

---

src/assets/data/CNAsList.json

Update contact email for Wordfence CNA for the 3/8/22 release

Content rjr 920

---

src/assets/data/news.json

Add 1 News article @ the 3/2/22 Board minutes

Content rjr 923

---

src/assets/data/events.json
src/assets/data/news.json
src/components/FooterModule.vue
src/mixins/dateMixins.js
src/views/Media/Events.vue
src/views/ProgramOrganization/WorkingGroups.vue
src/views/ResourcesSupport/Resources.vue

Content rjr 936

---

src/assets/data/CNAsList.json
src/assets/data/events.json
src/assets/data/news.json
src/components/FooterModule.vue
src/mixins/dateMixins.js
src/views/Media/Events.vue
src/views/ProgramOrganization/WorkingGroups.vue
src/views/ResourcesSupport/Resources.vue

Add 1 new CNA + 1 news article @ the new CNA

Content rjr 931

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Update broken links in CNAs list

Content rjr 898

---

src/assets/data/faqs.json

The other links are in the same section of the FAQs page

#957 Update 1 FAQ answer and links in other FAQs

---

src/assets/data/faqs.json

Update 1 FAQ answer and links in other FAQs. The other links are in the same section of the FAQs page.

Content rjr 957

---

src/assets/data/news.json

Add 1 news article @ 3/30/22 Board minutes

Content rjr 974

---

src/assets/data/CNAsList.json
src/assets/data/news.json

1. Add 1 new CNA.
2. Add 1 new announcement article to News page.
3. No CNA Map update.

#990 Add 1 new CNA + 1 new News article

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#995 Add 1 new CNA + 1 News annoucement

---

src/assets/data/news.json

Content rjr 996

---

src/assets/data/CNAsList.json

Update 1 CNA name: Facebook to Meta

Content rjr 1024

---

src/assets/data/news.json

Add 1 News article @ 4/27/22 Board minutes

Content rjr 1030

---

src/views/About/Overview.vue

Update Overview to add 4 additional embedded "About CVE" topic podcasts

Content rjr 1018

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Please note that this company's legal name uses "Corp".

#1029 Add 1 new CNA + 1 new News announcement

---

src/assets/data/news.json

Add 1 new Our CVE Story blog article

Content rjr 1041

---

src/assets/data/CNAsList.json

Content rjr 1050

---

src/assets/data/news.json

Add 1 new News article + edit 1 article title so it matches the update YouTube video title card.

Content rjr 1053

---

src/views/About/RelatedEfforts.vue

Add CWE SIGs & WGs to Related Efforts page

Content rjr 1067

---

src/assets/data/CNAsList.json
src/assets/data/currentBoardMembersList.json

Update 3 CNAs info + 1 Board Member info

Content rjr 1065

---

src/assets/data/CNAsList.json

Content rjr 1063

---

src/assets/data/CNAsList.json
src/assets/data/currentBoardMembersList.json
src/assets/data/news.json

Add 1 new CNA + 1 new News article

Content rjr 1077

---

src/assets/data/events.json

Content rjr 1079

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Add 4 new CNAs + 4 news announcements

Content rjr 1093

---

src/assets/data/events.json

Content rjr 1107

---

src/assets/data/news.json
src/views/Media/News/NewsArchives.vue

Content rjr 1113

---

src/assets/data/events.json
src/views/ProgramOrganization/WorkingGroups.vue

Update OCWG recurring meeting day & time:
1. Events page
2. Working Groups page

Content rjr 1119

---

src/assets/data/CNAsList.json

Update Hitachi Vantara disclosure policy url

Content rjr 1126

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1133 Add 1 new CNA + 1 News announcement article

---

src/components/HomeModule.vue

Update terminology in Access box on homepage

Content rjr 248

---

src/views/About/Metrics.vue

Add Q2-2022 stats to Metrics page

Content rjr 1174

---

src/assets/data/news.json

For the 8/3/22 Board meeting minutes

#1189 Add 1 new article to News page

---

src/assets/data/events.json

Content rjr 1243

---

src/assets/data/events.json
src/views/ProgramOrganization/WorkingGroups.vue

#1239 Update SPWG meeting day of week

Content rjr 1239

---

src/assets/data/CNAsList.json

#1242 Update Cisco's partner details page info

Content rjr 1242

---

src/assets/data/CNAsList.json
src/assets/data/events.json
src/views/ProgramOrganization/WorkingGroups.vue

#1250 Update 1 Partner Details pg

Content rjr 1250

---

src/assets/data/CNAsList.json
src/assets/data/events.json
src/assets/data/news.json
src/views/ProgramOrganization/WorkingGroups.vue

#1259 Add 1 Blog article & 1 News article

Content rjr 1259

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Content rjr 1270

---

src/assets/data/currentBoardMembersList.json
src/views/ProgramOrganization/Board.vue

#1217 Move 1 member to Emeritus past members

Content rjr 1217

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1280 Add 1 new CNA & announcement article

Content rjr 1280

---

src/assets/data/events.json
src/views/ProgramOrganization/WorkingGroups.vue

#1289 Update SPWG's meeting recurrence

Content rjr 1289

---

src/components/ExternalLinkMessage.vue
src/components/HomeModule.vue
src/components/NewsModule.vue
src/main.js
src/views/About/History.vue
src/views/About/RelatedEfforts.vue
src/views/CVERecord.vue
src/views/Media/News/NewsItem.vue
src/views/PartnerInformation/ListofPartners.vue
src/views/PartnerInformation/PartnerDetails.vue
src/views/ProgramOrganization/Board.vue
src/views/ProgramOrganization/ProgramRelationshipwithPartners.vue
src/views/ProgramOrganization/Structure.vue
src/views/ProgramOrganization/WorkingGroups.vue
src/views/ResourcesSupport/FAQs.vue
src/views/ResourcesSupport/Resources.vue
src/views/SiteSearch.vue

Created global component for external link help text and updated pages to use the component

#1271 Normalize help text for external links

---

src/assets/data/events.json

Update the 9/29/22 event url & details

#1309 Update 1 event url & description

---

src/components/PrimaryNavigation.vue
src/router/index.js

AC:
- updated CVE ID lookup pane
- CVE Record page is inaccessible

#1342 update CVE ID lookup pane

---

src/assets/data/NotificationBanner.json

Reverts CVEProject/cve-website#1344

Revert "#1333 Add temp banner message @ downtime"

---

src/assets/data/news.json
src/views/CVERecord/PublishedRecord.vue
src/views/CVERecord/RejectedRecordOrId.vue
src/views/CVERecord/ReservedId.vue
src/views/Downloads.vue

Update text of 1 Blog article & 4 Notification messages

Content rjr 1375

---

src/assets/data/news.json

#1297 3 new & 2 updated News articles

Content rjr 1297

---

src/assets/data/CNAsList.json

#1306 Update email & advisories link for 1 CNA

Content rjr 1306

---

src/assets/data/events.json

Update the 9/29/22 event url & details

Content rjr 1309

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1313 Add 1 CNA & update 3 CNAs

Content rjr 1313

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1329 Add 1 new CNA & news announcement

Content rjr 1329

---

src/assets/data/news.json

#1398 Add 1 Blog article @ Our CVE Stories series

Content rjr 1398

---

src/assets/data/NotificationBanner.json
src/assets/data/news.json
src/components/HomePageSidebarModule.vue
src/components/NewsModule.vue
src/mixins/dateMixins.js
src/views/Media/Events.vue
src/views/Media/News/BlogArchives.vue
src/views/Media/News/NewsItem.vue

Content rjr 1437

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1454 Add 3 new CNAs + news & 1 CNA article update

Content rjr 1454

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1468 Update 4 CNAs + add 1 new CNA

---

src/views/About/Overview.vue
src/views/ResourcesSupport/Resources.vue

#1449 Update CNA section of Resources page

Content rjr 1449

---

src/assets/data/news.json
src/components/HomePageSidebarModule.vue
src/components/NewsModule.vue
src/views/Media/News/NewsItem.vue
src/views/ResourcesSupport/Resources.vue

#1476 Workshop videos news item+2 Resources links
+
3 vue pages to add support for &amp;

Content rjr 1476

---

src/views/About/Metrics.vue

#1484 Update Metrics page with Q3-2022 stats

Content rjr 1484

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1498 Add 1 new CNA w/News announcement

Content rjr 1498

---

src/assets/data/news.json

Content rjr 1501

---

src/assets/data/news.json

Content rjr 1507

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Also, fixed policy link for 1 CNA

#1510 Add 1 new CNA w/News item + new OS category

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1523 Add 1 new CNA w/News article + Update 2 CNAs

Content rjr 1523

---

src/assets/data/CNAsList.json

#1531 Update 1 CNA contact email address

Content rjr 1531

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1565 Add 1 new CNA + update 2 links for 1 CNA

Content rjr 1565

---

src/assets/data/news.json

Also, correct 1 typo in previous Board Minutes article.

#1566 add 1 News page article @ Board Minutes

---

src/assets/data/news.json

#1566 add 1 News page article @ Board Minutes + correct 1 typo in previous Board Minutes article

Content rjr 1566

---

src/assets/data/CNAsList.json
src/assets/data/metrics.json
src/assets/data/news.json
src/assets/style/globals.scss
src/views/About/Metrics.vue
src/views/PartnerInformation/ListofPartners.vue

Content rjr 1578

---

src/assets/data/CNAsList.json
src/assets/data/metrics.json
src/assets/data/news.json
src/assets/style/globals.scss
src/views/About/Metrics.vue
src/views/PartnerInformation/ListofPartners.vue

#1579 Add 1 new CNA w/announcement article

Content rjr 1579

---

src/assets/data/currentBoardMembersList.json

#1591 Update 1 Board member's organization

Content rjr 1591

---

src/assets/data/CNAsList.json

#1613 Update 1 CNA's contact email

Content rjr 1613

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1621 Add 1 new CNA + News announcement

Content rjr 1621

---

src/assets/data/news.json

#1636 Add 1 new News page article

Content rjr 1636

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1651 Add 1 new CNA+1 news article

Content rjr 1651

---

src/views/ResourcesSupport/Resources.vue

#1646 Update CNA section of Resources page

Content rjr 1646

---

src/assets/data/NotificationBanner.json
src/views/Downloads.vue

#1658 Add Downloads table anchor + fix text/links

Content rjr 1658

---

src/assets/data/events.json
src/components/HomePageSidebarModule.vue
src/views/CVERecord/PublishedRecord.vue
src/views/Media/Events.vue
src/views/ProgramOrganization/WorkingGroups.vue

#1663 Update new day/time of OCWG monthly meeting on: (1) Events page, and (2) WGs page

Content rjr 1663

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1678 Add 1 new CNA + Update 1 CNA advisories link

Content rjr 1678

---

src/assets/data/news.json

#1694 Add 1 new News article @ Board minutes

Content rjr 1694

---

src/views/CVERecord/PublishedRecord.vue

Reverts CVEProject/cve-website#1668

Revert "#1667 display defaultStatus unknown when no information is provided"

---

src/assets/data/CNAsList.json
src/assets/data/news.json
src/views/ProgramOrganization/CNAs.vue

#1722 Add 1 new CNA+Update 1 Root scope+CNA pg text update

Content rjr 1722

---

src/assets/data/CNAsList.json
src/assets/data/news.json
src/components/PrimaryNavigation.vue
src/main.js
src/views/CVERecord/PublishedRecord.vue
src/views/ProgramOrganization/CNAs.vue
src/views/SiteSearch.vue

#1737 Add 1 News article about Board minutes

Content rjr 1737

---

src/assets/data/CNAsList.json
src/assets/data/news.json
src/components/PrimaryNavigation.vue
src/main.js
src/views/CVERecord/PublishedRecord.vue
src/views/ProgramOrganization/CNAs.vue
src/views/SiteSearch.vue

#1741 Add 1 new CNA + 1 News announcement

Content rjr 1741

---

src/assets/data/CNAsList.json
src/assets/data/faqs.json
src/assets/data/news.json
src/components/PrimaryNavigation.vue
src/main.js
src/views/CVERecord/PublishedRecord.vue
src/views/PartnerInformation/ListofPartners.vue
src/views/ProgramOrganization/CNAs.vue
src/views/SiteSearch.vue

#1735 Update ListofPartners vue text + 2 FAQs

Content rjr 1735

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1765 Add 1 new CNA + 1 announcement News article

Content rjr 1765

---

src/assets/data/CNAsList.json

#1746 Make full links in CNA scopes clickable

Content rjr 1746

---

src/assets/data/CNAsList.json
src/assets/data/news.json
src/views/PartnerInformation/Partner.vue

Content rjr 1771

---

src/assets/data/events.json

#1776 Update RSA booth url on Events page

Content rjr 1776

---

src/assets/data/events.json

#1789 Update 2 items on Events page

Content rjr 1789

---

src/assets/data/news.json

#1778 Add 1 News article @ Board Meeting Minutes

Content rjr 1778

---

src/assets/data/CNAsList.json

#1800 Update scope & replace 2 links for 1 CNA

Content rjr 1800

---

src/assets/data/currentBoardMembersList.json
src/assets/data/navigation.json
src/assets/data/news.json
src/components/PrimaryNavigation.vue
src/views/Downloads.vue

#1805 Update 1 Board member's affiliation

Content rjr 1805

---

src/assets/data/faqs.json
src/assets/data/navigation.json
src/assets/data/news.json
src/components/PrimaryNavigation.vue
src/views/Downloads.vue

Content rjr 1818

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Content rjr 1813

---

src/assets/data/news.json

#1815 Add 2 new News page articles

Content rjr 1815

---

src/assets/data/navigation.json
src/views/ProgramOrganization/WorkingGroups.vue

Update page text and on-page navigation label

Content rjr 1839

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Content rjr 1837

---

src/components/PrimaryNavigation.vue
src/views/CVERecord/PublishedRecord.vue

Survey is now closed. Remove survey link from website.

#1861 remove search feedback survey from site

---

src/views/ResourcesSupport/AllResources/CveServices.vue

#1876 Update CVE Services page text and links

Content rjr 1876

---

src/assets/data/NotificationBanner.json

#1879 Update masthead alert text & links

Content rjr 1879

---

src/assets/data/news.json

#1878 Add 2 News articles & update 1 Blog

Content rjr 1878

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#1875 Add 2 new CNAs + Update 2 CNA's info

Content rjr 1875

---

src/assets/data/CNAsList.json
src/assets/data/NotificationBanner.json
src/assets/data/events.json
src/assets/data/news.json
src/views/CVERecord/PublishedRecord.vue
src/views/CVERecord/RejectedRecordOrId.vue
src/views/CVERecord/ReservedId.vue
src/views/ResourcesSupport/AllResources/CveServices.vue

Content rjr 1898

---

src/assets/data/CNAsList.json
src/assets/data/NotificationBanner.json
src/assets/data/metrics.json
src/assets/data/news.json
src/views/CVERecord/PublishedRecord.vue
src/views/CVERecord/RejectedRecordOrId.vue
src/views/CVERecord/ReservedId.vue
src/views/ResourcesSupport/AllResources/CveServices.vue

#1890 Update Metrics page for Q1 CY 2023

Content rjr 1890

---

src/assets/data/CNAsList.json
src/assets/data/NotificationBanner.json
src/assets/data/news.json
src/views/CVERecord/PublishedRecord.vue
src/views/CVERecord/RejectedRecordOrId.vue
src/views/CVERecord/ReservedId.vue
src/views/ResourcesSupport/AllResources/CveServices.vue
src/views/ResourcesSupport/Resources.vue

Content rjr 1894

---

src/assets/data/CNAsList.json
src/assets/data/news.json

Content rjr 1897

---

src/assets/data/CNAsList.json
src/assets/data/news.json
src/views/ResourcesSupport/AllResources/CveServices.vue
src/views/ResourcesSupport/Resources.vue

Content rjr 1914

---

src/assets/data/faqs.json
src/views/About/RelatedEfforts.vue
src/views/ResourcesSupport/AllResources/ReserveIDsPublishRecords.vue
src/views/ResourcesSupport/Resources.vue

#1916 Update text & links on 4 pages

Content rjr 1916

---

src/assets/data/news.json

#1891 Add 1 News article + trailing lints cleanup

Content rjr 1891

---

src/assets/data/news.json

Content rjr 1838

---

src/assets/data/faqs.json
src/assets/data/news.json
src/views/About/RelatedEfforts.vue
src/views/ResourcesSupport/AllResources/ReserveIDsPublishRecords.vue
src/views/ResourcesSupport/Resources.vue

#1937 Add 1 News page article

---

src/assets/data/events.json

Reverts CVEProject/cve-website#1986

Revert "#1982 Update 1 item on Events page"

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#2052 Add 1 new CNA + Update 1 CNA

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#2194 Add 2 new CNAs

---

src/assets/data/CNAsList.json
src/assets/data/news.json

#2202 Add 2 new CNAs + Update 1 CNA

---

public/index.html

Reverts CVEProject/cve-website#2335

Revert "#2334 revert script"

---

src/assets/data/news.json

@athu-tran It is not in the commit message, but I added an news article about the new board member to this PR as both news articles are board-related.  There are now 2 news articles for this PR.  There are now 2 news articles for this PR.

#2467 Add 1 News article @ Board Minutes

---

src/assets/data/glossaryEntries.json
src/views/About/Process.vue

#2487 Update Glossary page + Proces page

---

src/assets/data/events.json

#2711 Events page updated

---

src/views/Downloads.vue

#2709 Update Downloads page

---

src/assets/data/NotificationBanner.json

Hide the Masthead Banner Alert text (not the entire masthead banner).

#2829 Hide masthead banner

---

src/assets/data/news.json
src/views/ResourcesSupport/AllResources/CNARules.vue
src/views/ResourcesSupport/Resources.vue

Pages updated:
News (1 Blog & 2 News)
CNA Rules (information alert box)
Resources (CNAs Rules & Policies box)

#2885 Add 1 new Blog and 2 new News articles

---

src/assets/data/news.json

#2921 Add "CVE Board Charter Version 3.5"

---

src/assets/data/news.json
src/views/About/Overview.vue
src/views/ProgramOrganization/WorkingGroups.vue
src/views/ResourcesSupport/Resources.vue

Removed references to the CNA Mentoring Program for the 8/6/24 release on:
1. news.json
2. Resources vue
3. Overview vue
4. Working Groups vue

Content rjr 2976

---

src/views/ResourcesSupport/Resources.vue

Both Sprint 12s have work started on them, and I can't tell which is which here, so I included both.

#3317 Update Resources page to add 2 new CNA Workshop PDFs

---

src/components/cveRecordSearchModule.vue
src/router/index.js

SEO browser tab change for Dev. See #3282

#3258 browser tab shows record id (dev)

---

package-lock.json
package.json
src/main.ts
src/views/ReportRequest/ReportRequestForNonCNAs.vue

Adds Buefy
Adds auto-complete search box to locate CNAs for non-CNA reporting/requests
Closes #2922

Resolves #2922 - create CNA search box for non-CNA reporting/requests (int)

---

package-lock.json
package.json
src/main.ts
src/views/ReportRequest/ReportRequestForNonCNAs.vue

Adds Buefy
Adds auto-complete search box to locate CNAs for non-CNA reporting/requests

Resolves #2922 - create CNA search box for non-CNA reporting/requests (dev)

---

package-lock.json
package.json
src/main.ts
src/views/ReportRequest/ReportRequestForNonCNAs.vue

Reverts CVEProject/cve-website#3324.
Reverting to address build error.

Revert "Resolves #2922 - create CNA search box for non-CNA reporting/requests (int)"

---

src/components/PrimaryNavigation.vue
src/main.ts

Please see acceptance criteria and screenshots in the description of issue #3355 for expected behaviors.
`src/components/PrimaryNavigation.vue`
- add feedback link and icons
`src/main.ts`
- add lightbulb icon

Resolves #3355 add feedback link 

---

src/assets/data/CNAsList.json
src/assets/data/NotificationBanner.json
src/assets/data/metrics.json
src/assets/data/news.json
src/views/About/Metrics.vue
src/views/SiteSearch.vue

* #3344 Add CVE Record Keyword Search text instruction to Search Website page
* #3448 Add 1 News article @ CNA Liaison Board Member reelected
* #3447 CNA Enrichment Recognition List for 2/10/25
* #3446 Add 3 new CNAs + Update 1 CNA's info + Add end periods to all CNA scopes for consistency
* #3449 Add 1 new Alert @ correcting date fields in 3,500 CVE Records

2/11/25 Release: INT to MAIN

---

src/assets/data/CNAsList.json
src/assets/data/metrics.json
src/assets/data/news.json
src/views/Media/News/BlogArchives.vue

* #3455 Add 1 new News article for 1/22/25 Board Minutes
* #3458 Add 5 Blog Archive PDFs
* #3457 Add 3 new CNAs + Update 2 CNA's info
* #3459 Add 1 new Blog

2/18/25 Release: INT to MAIN

---

src/assets/data/CNAsList.json
src/assets/data/metrics.json
src/assets/data/news.json

* #3480 Add 1 News item @ the 2/5/25 Board Minutes
* #3481 Add 1 new Blog about a Survey
* #3487 Update 1 Blog and Metrics page
* #3481 Update survey blog
* #3479 Update 5 CNA's info
* #3481 Update Blog about the survey
* #3481 Update survey blog text

3/4/25 Release: INT to MAIN

---

src/assets/data/CNAsList.json
src/assets/data/metrics.json
src/assets/data/news.json
src/views/ResourcesSupport/AllResources/CNARules.vue
src/views/ResourcesSupport/Resources.vue

* #3556 Add 3 new CNAs + Update 2 CNA's info
* #3556 Metrics page and News page for Add 3 new CNAs + Update 2 CNA's info
* #3557 Add PDF, News item, & Banner Alert message @ update to CNA Rules v4.1.0
* #3556 Update for website style
* #3556
* #3556Update News IDs

5/13/25 Release: INT to MAIN

---

src/assets/data/CNAsList.json
src/assets/data/metrics.json
src/assets/data/news.json
src/views/About/Metrics.vue
src/views/About/Overview.vue

* #3630 Update "CNA Enrichment Recognition List" info for 7/7/25 list
* #3631 Update Overview page
* #3629 Add 1 new CNA + Update 4 CNA's info

7/8/25 Release: INT to MAIN

---

src/assets/data/CNAsList.json
src/assets/data/metrics.json
src/assets/data/news.json
src/components/AdpVulnerabilityEnrichment.vue
src/components/ProductStatus.vue
src/views/ProgramOrganization/Archives.vue
src/views/ProgramOrganization/WorkingGroups.vue
src/views/ResourcesSupport/AllResources/CveServices.vue

* #3689 Update CVE Services page
* #3690 Update WGs page
* #3688 Add  new CNA
* #3690 Update WGs page
* #3688 Update 1 CNA's info
* archives: use "meetingArchivePath" variable to replace hard-coded values
* news: change cve.mitre.org based links to archived meeting summaries, etc.
* add scroll box for product status in CVE record display
---------

9/9/25 Release: INT to MAIN
